version: "3.3"
services:
  vidbox:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
    environment:
      # https://stackoverflow.com/questions/57213611/keycloak-and-spring-boot-web-app-in-dockerized-environment
      # Need fully qualfied url, or edit /etc/hosts with alias.
      # Otherwise application wont redirect properly
      KEYCLOAK_AUTH-SERVER-URL: http://keycloak:8090/auth
      KEYCLOAK_REALM: vidbox
      KEYCLOAK_RESOURCE: vidbox
      KEYCLOAK_PUBLIC-CLIENT: "true"
      KEYCLOAK_PRINCIPAL-ATTRIBUTE: preferred_username
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./ci:/opt/jboss/keycloak/imports
    command: ["-Djboss.socket.binding.port-offset=10"]
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "8090:8090"

